export type AboutTabId = 'fortsul' | 'historia' | 'missao' | 'visao' | 'valores' | 'sustentabilidade'

export type AboutValueItem = { title: string; text: string }

export type AboutTab = {
  id: AboutTabId
  navLabel: string
  eyebrow: string
  title: string
  paragraphs: string[]
  highlight: string
  values?: AboutValueItem[]
}

export const aboutTabs: AboutTab[] = [
  { id: 'fortsul', navLabel: 'FortSul', eyebrow: 'Sobre a FortSul', title: 'Mais de 15 anos levando tecnologia, eficiência e praticidade ao homem do campo.', paragraphs: ['A FortSul SC é uma indústria especializada no desenvolvimento e fabricação de máquinas, equipamentos e soluções para o setor agrícola.', 'Há mais de 15 anos, trabalhamos para transformar os desafios do campo em soluções mais eficientes, produtivas e acessíveis, contribuindo diretamente para a evolução do agronegócio brasileiro.', 'Nossa história é construída ao lado do produtor rural, entendendo as necessidades de cada atividade e desenvolvendo equipamentos que unem tecnologia, resistência, qualidade e praticidade.', 'Mais do que fabricar máquinas, buscamos oferecer soluções que ajudam o produtor a otimizar seu trabalho, reduzir custos e aumentar a eficiência de suas atividades.'], highlight: 'FortSul: tecnologia e força para quem move o campo.' },
  { id: 'historia', navLabel: 'Nossa História', eyebrow: 'Nossa história', title: 'Uma história construída com trabalho, inovação e compromisso com o campo.', paragraphs: ['A FortSul SC nasceu com o propósito de desenvolver equipamentos capazes de facilitar o trabalho no campo e acompanhar a evolução do agronegócio brasileiro.', 'Localizada às margens da SC-108, na cidade de Orleans, Santa Catarina, a empresa consolidou sua trajetória através do desenvolvimento de produtos de alta qualidade, tecnologia e excelente custo-benefício.', 'Ao longo dos anos, ampliamos nossa atuação e conquistamos espaço no mercado agrícola, levando nossas soluções para diferentes regiões do Brasil, com forte presença especialmente na Região Sul.', 'Nossa evolução é resultado da busca constante por inovação, melhoria de processos e, principalmente, da confiança construída junto aos nossos clientes, parceiros e fornecedores.', 'Hoje, seguimos olhando para o futuro, investindo em tecnologia e desenvolvendo equipamentos preparados para atender às novas demandas do campo.'], highlight: 'Nossa história começou no Sul do Brasil e continua crescendo ao lado do agronegócio brasileiro.' },
  { id: 'missao', navLabel: 'Missão', eyebrow: 'Nossa missão', title: 'Nossa Missão', paragraphs: ['Desenvolver e fornecer máquinas e equipamentos agrícolas que atendam às necessidades do produtor rural com qualidade, eficiência, tecnologia e confiabilidade.', 'Buscamos superar as expectativas dos nossos clientes por meio de soluções que proporcionem maior produtividade, praticidade e segurança para as atividades realizadas no campo.', 'Nosso compromisso é transformar conhecimento, experiência e inovação em equipamentos que contribuam para um agronegócio cada vez mais forte e eficiente.'], highlight: 'Qualidade + Tecnologia + Eficiência + Confiança' },
  { id: 'visao', navLabel: 'Visão', eyebrow: 'Nossa visão', title: 'Nossa Visão', paragraphs: ['Ser reconhecida como uma empresa de referência no desenvolvimento de máquinas e equipamentos para o setor agrícola, destacando-se pela qualidade dos produtos, inovação e excelência no relacionamento com os clientes.', 'Nossa visão é contribuir para um agronegócio mais eficiente, moderno e sustentável, oferecendo soluções capazes de reduzir custos, otimizar processos e melhorar o desempenho das atividades agrícolas.', 'Queremos continuar crescendo junto com nossos clientes, acompanhando as transformações do mercado e investindo constantemente em novas tecnologias.'], highlight: 'Evoluir constantemente para ajudar o campo a produzir cada vez melhor.' },
  { id: 'valores', navLabel: 'Valores', eyebrow: 'Nossos valores', title: 'Nossos Valores', paragraphs: [], highlight: '', values: [{ title: 'Ética e Transparência', text: 'Construímos relações baseadas na confiança, honestidade e responsabilidade.' }, { title: 'Trabalho em Equipe', text: 'Acreditamos que grandes resultados são construídos através da colaboração entre pessoas.' }, { title: 'Respeito', text: 'Valorizamos as pessoas, as diferenças e todos aqueles que fazem parte da nossa história.' }, { title: 'Inovação', text: 'Buscamos constantemente novas tecnologias e soluções para acompanhar a evolução do agronegócio.' }, { title: 'Relacionamento', text: 'Mantemos relações sólidas e duradouras com clientes, fornecedores e parceiros.' }, { title: 'Qualidade', text: 'Trabalhamos para garantir excelência em cada processo, produto e serviço oferecido.' }, { title: 'Desenvolvimento Sustentável', text: 'Buscamos crescer de forma responsável, contribuindo para um futuro mais eficiente e sustentável.' }] },
  { id: 'sustentabilidade', navLabel: 'Sustentabilidade', eyebrow: 'Sustentabilidade', title: 'Tecnologia para produzir hoje e construir o futuro.', paragraphs: ['Acreditamos que inovação e desenvolvimento devem caminhar junto com a responsabilidade.', 'Por isso, buscamos desenvolver equipamentos que contribuam para uma operação agrícola mais eficiente, reduzindo desperdícios, otimizando processos e aproveitando melhor os recursos disponíveis.', 'Nosso compromisso com o desenvolvimento sustentável está presente na busca constante por maior eficiência operacional, melhor aproveitamento dos recursos, redução de desperdícios, equipamentos mais duráveis e soluções que contribuam para a produtividade do campo.'], highlight: 'Desenvolver o presente com responsabilidade para fortalecer o futuro do agronegócio.' },
]
